<a href="https://colab.research.google.com/github/michaelcordero/cap-5602-ai/blob/master/homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   Student name: **[Michael Cordero]**
*   Student Panther ID: **[6331927]** 
*   Collaborator(s): **[Aseem Sharma]**
*   **Notice on Academic Misconduct**: Sharing your codes with other students is also an academic misconduct. If your submission is found unusually similar to that of another student, you will be reported to the SCAI as a potential academic misconduct case, regardless of your reasons. Violations may lead to suspension or expulsion from the university.

# CAP5602 Homework 1 (15% total grade)

## **Deadline: 9/19/2022 11:59 PM**

## Question 1: Convert vector of real numbers to probabilities (4% total grade)

Given a vector of real numbers $r = (r_1, r_2, ..., r_n)$. We can convert this vector into a probability vector $p = (p_1, p_2, ..., p_n)$ using the formulation: $ p_i = e^{r_i}/(\sum_{i=1}^n e^{r_i})$, for all $i$.

Write a Python function `vec_to_prob(r)` that takes the vector $r$ as input and returns the vector $p$. Both $r$ and $p$ will be numpy arrays. You can assume $r$ is non-empty.

Sample inputs and outputs:
*   **Input**: `np.array([4, 6])`, **output**: `[0.11920292, 0.88079708]`

*   **Input**: `np.array([3.4, 6.2, 7.1, 9.8])`, **output**: `[0.00151576, 0.02492606, 0.06130823, 0.91224995]`

In [1]:
# Write your function here
import math
import numpy as np


def vec_to_prob(r: np.array) -> np.array:
   exp = np.exp(r)
   p = exp / np.sum(exp)
   return p

Let's test your function. 

In [2]:
# Convert input from list to np.array first before calling your function to avoid errors
print(vec_to_prob(np.array([4, 6])))
print(vec_to_prob(np.array([3.4, 6.2, 7.1, 9.8])))
print(vec_to_prob(np.array([3, 5.5, 0])))

[0.11920292 0.88079708]
[0.00151576 0.02492606 0.06130823 0.91224995]
[0.07557276 0.92066469 0.00376255]


**Grader's comments:** Correct (4%)

## Question 2: Convert matrix of real numbers to probabilities (6% total grade)

Now we will extend Question 1 to matrices. Given a matrix of real numbers $R = (R_1, R_2, ..., R_m)$, where $R_i = (r_1, r_2, ..., r_n)$ is the i-th row of the matrix.

### Question 2a (4% total grade):

Write a Python function `mat_to_prob(R)` that returns the matrix $P = (P_1, P_2, ..., P_m)$ where $P_i$ is the i-th row of matrix $P$, and $P_i$ is the probability vector obtained from $R_i$ using the formulation in Question 1. In other words, convert each row of the input matrix into a probability vector.

Sample inputs and outputs:
*   **Input**: `np.array([[4, 6], [3.5, 9.1]])`

    **Output**: `[[0.11920292, 0.88079708], [0.00368424, 0.99631576]]`

*   **Input**: `np.array([[2, 3.1, 5], [10, 3.7, 12], [4, 5.5, 0]]))`

    **Output**: `[[4.15115123e-02, 1.24707475e-01, 8.33781013e-01],
 [1.19176835e-01, 2.18844992e-04, 8.80604320e-01],
 [1.81818026e-01, 8.14851861e-01, 3.33011331e-03]]`

In [3]:
# Write your function here
def mat_to_prob(R: np.array) -> np.array:
    p: np.array = np.apply_along_axis(vec_to_prob, 1, R)
    return p

Let's test your function. 

In [4]:
# Convert input from 2-d list to np.array first before calling your function

print(mat_to_prob(np.array([[4, 6], [3.5, 9.1]])))
print(mat_to_prob(np.array([[2, 3.1, 5], [10, 3.7, 12], [4, 5.5, 0]])))

[[0.11920292 0.88079708]
 [0.00368424 0.99631576]]
[[4.15115123e-02 1.24707475e-01 8.33781013e-01]
 [1.19176835e-01 2.18844992e-04 8.80604320e-01]
 [1.81818026e-01 8.14851861e-01 3.33011331e-03]]


**Grader's comments:** Correct (4%)

### Question 2b (2% total grade):
In fact, the function above is called the `softmax` function, and scipy has an implementation for it. First, read the API at: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.softmax.html.

Then write code to apply this version of the `softmax` function on the sample matrices above and print out the results.

In [5]:
# The function has been imported for you
from scipy.special import softmax

# Write your code here
def scipy_mat_to_prob(R: np.array) -> np.array:
    p: np.array = np.apply_over_axes(softmax, R, 1)
    return p

**Grader's comments:** There is no code to apply your function to the sample matrices and print out the results. (1%)

## Question 3: Vector scaling (5% total grade)

Given a vector of real numbers $r = (r_1, r_2, ..., r_n)$. We can standardize the vector using the formulation: $v_i = \frac{r_i - m}{s}$, where $m$ is the mean of the vector $r$, and $s$ is the standard deviation of $r$. The vector $v = (v_1, v_2, ..., v_n)$ will be the scaled vector.

Write a Python function `scale_vec(r)` that takes the vector $r$ as input and returns the scaled vector $v$.

Sample inputs and outputs:
*   **Input**: `np.array([1, 3, 5])`, **output**: `[-1.22474487, 0., 1.22474487]`
*   **Input**: `np.array([3.3, 1.2, -2.7, -0.6])`, **output**: `[1.35457092, 0.40637128, -1.35457092, -0.40637128]`

In [6]:
# Write your function here
def scale_vec(r: np.array) -> np.array:
    m = np.mean(r)
    s = np.std(r)
    q: np.array = (r - m) / s  # broadcasting
    return q

Let's test your function.

In [7]:
import numpy as np

print(scale_vec(np.array([1, 3, 5])))
print(scale_vec(np.array([3.3, 1.2, -2.7, -0.6])))

[-1.22474487  0.          1.22474487]
[ 1.35457092  0.40637128 -1.35457092 -0.40637128]


**Grader's comments:** Correct (5%)